# Generated by Django 5.2.4 on 2025-07-26 15:30

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата, на которую забронирован столик")),
                ("time", models.TimeField(verbose_name="Время, на которое забронирован столик")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий к бронированию")),
                ("is_active", models.BooleanField(default=True, verbose_name="Бронь активна")),
                ("reminder_sent", models.BooleanField(default=False, verbose_name="Напоминание отправлено")),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    image_cropping.fields.ImageCropField(
                        blank=True, null=True, upload_to="restaurant/images", verbose_name="Изображение столика"
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "image",
                        "0x0",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=True,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="cropping",
                    ),
                ),
                ("number", models.PositiveIntegerField(null=True, verbose_name="Номер столика")),
                ("number_of_seats", models.PositiveSmallIntegerField(verbose_name="Количество мест")),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя сотрудника")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия сотрудника")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Владелец", "Владелец"),
                            ("Управляющий", "Управляющий"),
                            ("Шев-повар", "Шев-повар"),
                            ("Су-шеф", "Су-шев"),
                            ("Повар", "Повар"),
                            ("Администратор зала", "Администратор зала"),
                            ("Официант", "Официант"),
                            ("Бармен", "Бармен"),
                        ],
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "avatar",
                    image_cropping.fields.ImageCropField(
                        blank=True, null=True, upload_to="restaurant/workers/images", verbose_name="Фото сотрудника"
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "avatar",
                        "0x0",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=True,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="cropping",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание сотрудника")),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["id"],
            },
        ),
    ]
