# Generated by Django 5.2.4 on 2025-07-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гость",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.table",
                verbose_name="Забронированный столик",
            ),
        ),
    ]
